name: CI/CD

on:
  push:
    branches: [ "main" ] # Sur push main => déploiement Staging
    tags: [ "v*" ] # Sur tag v* => déploiement Prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with GCP Artifact Registry
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev

    - name: Build docker image
      run: |
        docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadatafrontend/pharmadatafrontend:$GITHUB_SHA \
        --build-arg API_URL=${{ secrets.STAGING_API_URL }} .
    
    - name: Push docker image
      run: |
        docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadatafrontend/pharmadatafrontend:$GITHUB_SHA

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/main'
      env:
        API_URL: STAGING_API_URL
      run: |
        gcloud run deploy pharmadata-frontend-staging \
          --image europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadatafrontend/pharmadatafrontend:$GITHUB_SHA \
          --platform managed \
          --region europe-west1 \
          --set-env-vars ENVIRONMENT=staging \
          --set-env-vars API_URL=${{ secrets.STAGING_API_URL }} \
          --allow-unauthenticated

    - name: Deploy to Prod
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        API_URL: PROD_API_URL
      run: |
        gcloud run deploy pharmadata-frontend-prod \
          --image europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadatafrontend/pharmadatafrontend:$GITHUB_SHA \
          --platform managed \
          --region europe-west1 \
          --set-env-vars API_URL=${{ secrets.PROD_API_URL }} \
          --allow-unauthenticated